- name: nginx install and run
  hosts: web
  become: true #become to root user
  tasks:
  - name: install nginx
    ansible.builtin.package: #heterogeneous package manager
      name: nginx
      state: present