- name: variables to print
  hosts: web
  vars:
    name: "Shanmukh"
    age: "25"
    location: "India"
  tasks: 
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, my name is {{ name }} and I am {{ age }} years old and I live in {{ location }}."