- name: variables to print
  hosts: web
  vars: #play level , all tasks in this play can access these variables
    name: "Shanmukh"
    age: "25"
    location: "India"
  tasks: 
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, my name is {{ name }} and I am {{ age }} years old and I live in {{ location }}."

  - name: print the information again
    vars: #task level, only this task can access these variables
      name: "Shannu"
      age: "25"
      location: "India"
    ansible.builtin.debug:
      msg: "Hi, my name is {{ name }} and I am {{ age }} years old and I live in {{ location }}."