- name: devops cousre information
  hosts: local
  connection: local # local connection
  vars:
   name: "Shanmukh from files"
   age: "25"
  location: "India"
  topics: #list
    - Linux
    - Ansible
    - Terraform 
    - AWS
  live: true
  tools:
    - name: "AWS"
      version: "2023"
      type: "cloud"
    - name: "Terraform"
      version: "2023"
      type: "cloud"
    - name: "Ansible"
      version: "2023"
      type: "automation"
  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "Hi, my name is {{ name }} and I am {{ age }} years old and I live in {{ location }}."
    - name: print the topics
      ansible.builtin.debug:
        msg: "The topics are {{ topics }}"
    - name: print the tools
      ansible.builtin.debug:
        msg: "The tools are {{ tools }}"
    - name: print the tools version
      ansible.builtin.debug:
        msg: "The tools version is {{ item.version }}"
      loop: "{{ tools }}"
